### ISSUE TITLE
Send a db report to an email feature

### ISSUE THREAD

**Issue by hakoemmy** [victkarangwa/psql-backup-cron#1]
### Is your feature request related to a problem?
>  Yes, after generating a database report, there should be a way of sending the backup SQL file to the email for future reference
### Describe the solution you'd like
> So simple, it's a matter of setting up an email service, we can for example use ```nodemailer``` 
### Additional context
> N/A

**Comment by hakoemmy** [comment]
@victkarangwa Let me know if the above feature makes sense, have it approved then I can contribute

**Comment by victkarangwa** [comment]
This makes sense and could be an awesome feature @hakoemmy

**Comment by hakoemmy** [comment]
@victkarangwa this PR https://github.com/victkarangwa/psql-backup-cron/pull/2 fixes this issue.
